Increment5
rodeorm/shortener pull request #4
Opened 2022-04-12 12:09 UTC by rodeorm

2022-04-15 12:57 UTC, lugingf requested changes
Все очень круто. Предлагаю чуть-чуть подкорректировать структуру

2022-04-15 12:57 UTC, lugingf commented on cmd/shortener/config.go
> +	var sa, bu, fsp string
Давай развернем названия переменных. Я, например, с хочу не могу распарсить что они означают

2022-04-15 12:57 UTC, lugingf commented on internal/control/apiShortenHandler.go
> +	shortURLKey, _ := h.Storage.InsertShortURL(url.Key)
я бы все, что с `logic.` спрятал бы под капот и унес бы из хэндлера

2022-04-15 12:57 UTC, lugingf commented on internal/control/gzip.go
> +func DecompressGzip(data []byte) ([]byte, error) {
я бы это оставил в мидлваре, тоже отдельными функциями, но в рамках пакета midleware, тем более что, кажется, кроме как там эти функции не используются

2022-04-15 12:57 UTC, lugingf commented on internal/repo/abstract.go
> +	container.Singleton(func() AbstractStorage {
А для чего нам тут понадобился контейнер?

2022-04-15 13:07 UTC, rodeorm commented on cmd/shortener/config.go
> +	var sa, bu, fsp string
Ок.  serverAddress, baseURL, fileStoragePath

2022-04-15 16:32 UTC, rodeorm commented on internal/control/apiShortenHandler.go
> +	shortURLKey, _ := h.Storage.InsertShortURL(url.Key)
Ок. Убрал все зависимости пакета control от logic.

2022-04-15 16:32 UTC, rodeorm commented on internal/control/gzip.go
> +func DecompressGzip(data []byte) ([]byte, error) {
Ок.

2022-04-15 16:32 UTC, rodeorm commented on internal/repo/abstract.go
> +	container.Singleton(func() AbstractStorage {
Просто игрался) Уберу

2022-04-15 16:33 UTC, rodeorm commented
> Все очень круто. Предлагаю чуть-чуть подкорректировать структуру

Спасибо за ревью, со всеми замечаниями согласен. Вроде все исправил

2022-04-16 11:09 UTC, lugingf commented on internal/repo/abstract.go
> +	container.Singleton(func() AbstractStorage {
Не, если игрался, то норм :) Сорри, если мой коммент тут показался рекомендацией

2022-04-16 11:10 UTC, lugingf approved these changes
Огонь, принято!

2022-04-17 10:05 UTC, merged